"$schema" = 'https://starship.rs/config-schema.json'

palette = "kanso_ink"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "muted"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](purple) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "muted"

[cmd_duration]
format = "[$duration]($style) "
style = "gold"

[python]
format = "[$virtualenv]($style) "
style = "muted"
detect_extensions = []
detect_files = []

[palettes.kanso_ink]
red = "#e46876"
green = "#87a987"
gold = "#e6c384"
blue = "#7fb4ca"
purple = "#938aa9"
cyan = "#7aa89f"
muted = "#717c7c"
